variables:
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src/ClientApp/ClientApp

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build
    workingDir: src/ClientApp/ClientApp

# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'angular'
#     targetPath: 'src/angular7/dist'